### ISSUE TITLE
Implement a method for modification of text lists in definitions.

### ISSUE THREAD

**Issue by JabJabJab** [JabJabJab/LangPack#10]
Write a solution to allow for string injection of multiple lines with modification of each line in a call with a string and the line being %line%.

Example:
```yml
  my_list:
    - 'This is line 1'
    - 'This is line 2'
  
  my_message: 'This is my list: lines(my_list, &6\t- %line%)'
```

This will require implementing a method-call solution to be implemented.
