### ISSUE TITLE
Implement relative path for section queries.

### ISSUE THREAD

**Issue by JabJabJab** [JabJabJab/LangPack#7]
Current Example: 
```yml
a_group:
  header: '[Header]'
  message: '%a_group.header% This is a message.'
```

LangPack should be able to provide a relative path.

```yml
a_group:
  header: '[Header]'
  message: '%header% This is a message.'
```

Look through the section's scope first before going through the package-query process.
